{% set name = "dynamicisttoolkit" %}
{% set version = "0.6.2" %}
{% set sha256 = "963aea9972ba19c55e5a6b51ce165adea2620f7ce2815ccc880b6c9687f37c15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base >=3.5.1
    - numpy >=1.21.5
    - python >={{ python_min }}
    - scipy >=1.8.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - dtk
    - dtk.bicycle
    - dtk.inertia
    - dtk.process
    - dtk.test

about:
  home: http://github.com/moorepants/dynamicisttoolkit
  license: Unlicense
  license_file: UNLICENSE.txt
  summary: 'Various tools for theoretical and experimental dynamics.'
  doc_url: http://dynamicisttoolkit.readthedocs.io/
  dev_url: https://github.com/moorepants/dynamicisttoolkit

extra:
  recipe-maintainers:
    - moorepants
