{% set name = "DynamicistToolKit" %}
{% set version = "0.6.0" %}
{% set sha256 = "4759667054aec4795a33d10fe2e5c831ab0b284684613cf35250cbb66610ad18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - matplotlib-base >=3.5.1
    - numpy >=1.21.5
    - python >=3.8
    - scipy >=1.8.0

test:
  imports:
    - dtk
    - dtk.bicycle
    - dtk.inertia
    - dtk.process
    - dtk.test

about:
  home: http://github.com/moorepants/dynamicisttoolkit
  license: Unlicense
  license_file: UNLICENSE.txt
  summary: 'Various tools for theoretical and experimental dynamics.'
  doc_url: http://dynamicisttoolkit.readthedocs.io/
  dev_url: https://github.com/moorepants/dynamicisttoolkit

extra:
  recipe-maintainers:
    - moorepants
