travis:
  secure:
    BINSTAR_TOKEN: SAOi2cyfYG0yO4j+4Tt5V0NYFGMTe8YqM44rN/Fl2xP7tlB8jRD022PwUitERU8PhIp9bWNCjCj9ZsKbV8Xu9rLSGoMMVdDdHME1UPQV+FPCMt+QthFEasHvIr0gYXQgHKz4kJKeUNSHmEeLIHwbKZHOqOQWkfKepQvMRDlykxu5nXGyt0bPRm7lR3ctA6mGJsA3jweqs3RG0xnlYTAsERnO/5OrvufmguYdiC06Z9FtwQud8iBdF6NgpWhbK7AC0TTZN7g7aQTqOfPS2Br3iFGQslYou5iIQgcosgQqLG2dC/Zak4ePykXyvHZCIeg1HRo3UmJI+4wvn4pca4i30ennhLA8Y3ZwCzWt/rSP5pXNx2mLihgd+ZgTHOMG80Zy3eMZUy8YxidIbDiSerdhOdDalsrgFFJmwuQov2MOtqsDniDmS3T2416NF7l/CLH+yr8pSmt46I9DlOHPx0Brj7lkXm4OEXF65j2aCJcFuKVmMLeUdtDtXHAeHINN5YlZTYMUJlzNmRYepN0Z+Nsyl33qmjxVceSiHvcZ/tAyvVfezNNq/a88ro8bX9AWfgqEnafiE9HRKhyP063ZyZmyc9peUHahWBJP8ckgbcJNvv1INtuiaXrDBP4patZtt/oERaWWOU+wpEL7pPxdM0JVb7lPo4iqWrUseaXSuZFljPE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
